### PR TITLE
Keep model in sync

### PR DESCRIPTION
**Pull request by evenfrost**
If a model data is loaded asynchronously (e.g. after module initialization), it fails to be handled properly: model is not updated, drake events are not registered. This change calls `handleModels` in model watcher and fixes the issue.

### CODE REVIEW

**Comment by luckylooke** [comment]
:+1:  thanks

**Comment by bevacqua** [comment]
@luckylooke made you a collaborator on npm so you can now use `npm run deploy` to publish updates

**Comment by evenfrost** [comment]
Great, thanks.

**Comment by luckylooke** [comment]
@bevacqua OK! :+1:

**Pull request merged**
